### Get manifest
GET http://localhost:3000/api/plugin/discover/meta/manifest

### Run query against datasource
POST http://localhost:3000/api/plugin/discover/datasource/elasticsearch/query
content-type: application/json

{
  "collection": "my_index"
}

